let comic1 = document.getElementById("containerComic1");
let comic2 = document.getElementById("containerComic2");
let comic3 = document.getElementById("containerComic3");
let comic4 = document.getElementById("containerComic4");
let comic5 = document.getElementById("containerComic5");
let comic6 = document.getElementById("containerComic6");
let comic7 = document.getElementById("containerComic7");
let comic8 = document.getElementById("containerComic8");
let comic9 = document.getElementById("containerComic9");
let comic10 = document.getElementById("containerComic10");
let comic11 = document.getElementById("containerComic11");
let comic12 = document.getElementById("containerComic12");
let comic13 = document.getElementById("containerComic13");
let comic14 = document.getElementById("containerComic14");
let comic15 = document.getElementById("containerComic15");
let comic16 = document.getElementById("containerComic16");
let comic17 = document.getElementById("containerComic17");
let comic18 = document.getElementById("containerComic18");
let selectorComic1 = document.getElementById("selectorComic1");
let selectorComic2 = document.getElementById("selectorComic2");
let selectorComic3 = document.getElementById("selectorComic3");
let selectorComic4 = document.getElementById("selectorComic4");
let selectorComic5 = document.getElementById("selectorComic5");
let selectorComic6 = document.getElementById("selectorComic6");
let selectorComic7 = document.getElementById("selectorComic7");
let selectorComic8 = document.getElementById("selectorComic8");
let selectorComic9 = document.getElementById("selectorComic9");
let selectorComic10 = document.getElementById("selectorComic10");
let selectorComic11 = document.getElementById("selectorComic11");
let selectorComic12 = document.getElementById("selectorComic12");
let selectorComic13 = document.getElementById("selectorComic13");
let selectorComic14 = document.getElementById("selectorComic14");
let selectorComic15 = document.getElementById("selectorComic15");
let selectorComic16 = document.getElementById("selectorComic16");
let selectorComic17 = document.getElementById("selectorComic17");
let selectorComic18 = document.getElementById("selectorComic18");



/*esto de add event listener lo unico que tiene diferente es que en lugar 
de usar onclick directamente en la etiqueta, lo ponemos aqi en JS, detecta 
cuangdo algo en nuestro html es cliqueado y ejecuta la funcion que se declara ahi mismo*/
selectorComic1.addEventListener('click', function(){
    comic1.style.display = "flex";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic2.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "flex";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic3.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "flex";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic4.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "flex";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic5.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "flex";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic6.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "flex";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic7.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "flex";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic8.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "flex";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic9.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "flex";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic10.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "flex";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic11.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "flex";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic12.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "flex";
    comic13.style.display = "none";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic13.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "flex";
    comic14.style.display = "none";
    comic15.style.display = "none";
    comic16.style.display = "none";
    comic17.style.display = "none";
    comic18.style.display = "none";
});
selectorComic14.addEventListener('click', function(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "flex";
});




function cerrar(){
    comic1.style.display = "none";
    comic2.style.display = "none";
    comic3.style.display = "none";
    comic4.style.display = "none";
    comic5.style.display = "none";
    comic6.style.display = "none";
    comic7.style.display = "none";
    comic8.style.display = "none";
    comic9.style.display = "none";
    comic10.style.display = "none";
    comic11.style.display = "none";
    comic12.style.display = "none";
    comic13.style.display = "none";
    comic14.style.display = "none";
}